version: '3.8'

services:
  whisperx:
    build: .
    image: whisperx-tesla-p4
    container_name: whisperx-tesla-p4
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    volumes:
      - ./videos:/app/videos
      - ./output:/app/output
    working_dir: /app/videos
    command: ["--help"]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
